/**
 * Live screen StyleSheet — kept separate so app/live.tsx stays logic-focused.
 */
import { StyleSheet } from "react-native";

export const liveStyles = StyleSheet.create({
  // Idle: dark shell. Matched: live.tsx switches rootMatched (transparent)
  // so Android SurfaceView is never covered by a solid #050608 slab.
  root: { flex: 1, backgroundColor: "#050608" },
  /** Transparent while matched — video must not sit under opaque RN bg */
  rootMatched: { flex: 1, backgroundColor: "transparent" },
  stage: {
    flex: 1,
    margin: 0,
    borderRadius: 0,
    // Transparent so Android SurfaceView (RTCView) isn't painted over
    backgroundColor: "transparent",
    borderWidth: 0,
    borderColor: "transparent",
    // overflow:hidden clipped SurfaceView on some Android devices → black
    overflow: "visible",
  },
  remoteFill: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "transparent",
    // Explicit size helps Android SurfaceView attach at full stage
    width: "100%",
    height: "100%",
  },
  /** Bars jail over partner main tile (RTCView zOrder 0 while active). */
  barsOnTile: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 20,
    overflow: "hidden",
  },
  barsOnTileCaption: {
    position: "absolute",
    bottom: 14,
    alignSelf: "center",
    color: "rgba(255,255,255,0.9)",
    fontSize: 12,
    fontWeight: "700",
    textShadowColor: "#000",
    textShadowRadius: 6,
    backgroundColor: "rgba(0,0,0,0.45)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    overflow: "hidden",
  },
  /** Bars on PiP (self when barred, or partner when views swapped). */
  barsOnPip: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 20,
    overflow: "hidden",
    borderRadius: 12,
  },
  /** Legacy static edge styles (unused — BrandWatermark owns layout + settle).
   * Live mark parks bottom-center of partner video after center hold. */
  brandWm: {
    position: "absolute",
    left: 8,
    bottom: 10,
    zIndex: 5,
    justifyContent: "center",
    alignItems: "flex-start",
    // Do not constrain width — full wordmark must stay readable in portrait shots
    maxWidth: undefined,
    overflow: "visible",
  },
  brandWmText: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 12.5,
    fontWeight: "700",
    letterSpacing: 0.4,
    // Horizontal only — never vertical writing / mid-word clip
    flexShrink: 0,
    textShadowColor: "rgba(0,0,0,0.8)",
    textShadowRadius: 4,
    textShadowOffset: { width: 0, height: 1 },
  },
  /** Transparent hit target over remote video (must not wrap RTCView). */
  remoteTapLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 3,
    backgroundColor: "transparent",
  },
  /** Soft veil + badge when you mute the partner (debate-style). */
  /** Soft mute scrim + centered icon only (no text chips). */
  partnerMuteOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 24,
    elevation: 12,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(18, 6, 4, 0.22)",
    borderWidth: 2,
    borderColor: "rgba(255, 100, 70, 0.35)",
  },
  partnerMuteWatermark: {
    fontSize: 56,
    opacity: 0.55,
    textShadowColor: "rgba(0,0,0,0.55)",
    textShadowRadius: 12,
  },
  partnerMuteWatermarkPip: {
    fontSize: 28,
    opacity: 0.55,
    textShadowColor: "rgba(0,0,0,0.55)",
    textShadowRadius: 8,
  },
  // Legacy badge styles (text chips removed — icon only)
  partnerMuteBadge: {},
  partnerMuteBadgePip: {},
  partnerMuteBadgeText: {},
  partnerMuteBadgeTextPip: {},
  /** Full-stage underlay under PartnerBlurVeil (never pure black / never transparent) */
  blurUnderlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#45536c",
    opacity: 1,
  },
  /** No solid black wall — transparent so RTCView / local cam can show through */
  videoPlaceholder: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
  },
  /** Full-stage brand loop under idle/search (PC remote-empty parity). */
  brandLoadingLoop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#050608",
    zIndex: 0,
    width: "100%",
    height: "100%",
  },
  /** Centered connecting card on empty remote stage (never pure black) */
  connectCard: {
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    paddingHorizontal: 24,
    minWidth: 220,
    maxWidth: 340,
    gap: 8,
    paddingVertical: 18,
    borderRadius: 18,
    // Readable mid-tone card while linking — not OLED black hole
    backgroundColor: "rgba(28, 40, 62, 0.88)",
    borderWidth: 1,
    borderColor: "rgba(140, 180, 255, 0.28)",
  },
  connectPulseOuter: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 2,
    borderColor: "rgba(100, 160, 255, 0.28)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
    backgroundColor: "transparent",
  },
  connectPulseInner: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(90, 150, 255, 0.35)",
  },
  pipVideo: {
    width: "100%",
    height: "100%",
    backgroundColor: "transparent",
  },
  /** Local cam Hidden badge on PiP */
  selfHiddenOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(8, 12, 20, 0.55)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 8,
  },
  selfHiddenBadge: {
    color: "#ffe8c8",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.4,
    textTransform: "uppercase",
    backgroundColor: "rgba(20, 12, 8, 0.85)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    overflow: "hidden",
  },
  selfHiddenMain: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "flex-end",
    paddingBottom: 48,
    zIndex: 8,
  },
  selfHiddenBadgeMain: {
    color: "#ffe8c8",
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0.5,
    textTransform: "uppercase",
    backgroundColor: "rgba(20, 12, 8, 0.82)",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 12,
    overflow: "hidden",
  },
  /** top padding applied at runtime via safe-area insets */
  overlay: {
    position: "absolute",
    left: 12,
    top: 0,
    right: 12,
    // In-stage only (search/idle labels, peer strip). Matched PartnerChrome is
    // chromeTopOverlay — sibling of stage so Android SurfaceView cannot cover it.
    // Partner RTCView must be zOrder 0; elevation cannot beat zOrder ≥ 1.
    zIndex: 100,
    elevation: 28,
    gap: 4,
  },
  /**
   * Matched partner name / stars / mute banners — root-level sibling of stage
   * (NOT under RTCView). Android SurfaceView eats in-stage RN elevation.
   * top/padding applied at runtime via safe-area insets.
   * Below privacy fullscreen (100000); above video and normal stage chrome.
   */
  /** Android Modal root — full screen, pass-through outside chrome card */
  chromeModalRoot: {
    flex: 1,
    backgroundColor: "transparent",
  },
  chromeTopOverlay: {
    position: "absolute",
    // Slim top-right only — leave left/center face clear (no full-width bar)
    right: 8,
    maxWidth: "55%",
    alignItems: "flex-end",
    zIndex: 99999,
    elevation: 99999,
    gap: 0,
    backgroundColor: "transparent",
  },
  /**
   * Partner flag chip — top-left of remote video, below identity name strip.
   * Partner RTCView is zOrder 0 so elevation ≥16 paints above SurfaceView.
   * top offset is applied at runtime (insets + dock height) from live.tsx.
   */
  partnerFlagChip: {
    position: "absolute",
    left: 10,
    top: 12,
    zIndex: 280,
    elevation: 20,
    minWidth: 40,
    minHeight: 40,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(4, 8, 16, 0.88)",
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.28)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.45,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
  },
  partnerFlagChipEmoji: {
    fontSize: 26,
    lineHeight: 30,
    includeFontPadding: false,
    textAlign: "center",
    textShadowColor: "rgba(0,0,0,0.55)",
    textShadowRadius: 3,
    textShadowOffset: { width: 0, height: 1 },
  },
  /** Two-letter ISO fallback when emoji unavailable */
  partnerFlagChipCode: {
    color: "#e8eef7",
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0.6,
    includeFontPadding: false,
    textAlign: "center",
  },
  /** Compact flag chip when partner is in PiP (swapped views) */
  partnerFlagChipPip: {
    position: "absolute",
    left: 6,
    top: 6,
    zIndex: 24,
    elevation: 16,
    minWidth: 28,
    minHeight: 28,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: "rgba(4, 8, 16, 0.88)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.25)",
    alignItems: "center",
    justifyContent: "center",
  },
  partnerFlagChipEmojiPip: {
    fontSize: 16,
    lineHeight: 18,
    includeFontPadding: false,
    textAlign: "center",
  },
  partnerFlagChipCodePip: {
    color: "#e8eef7",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.4,
    includeFontPadding: false,
  },
  /**
   * Match elapsed timer — bottom-left of partner conversationalist window
   * (replaces "Say hi in chat…" empty hint + bottom chrome timer chip).
   */
  partnerCallTimerChip: {
    position: "absolute",
    left: 10,
    bottom: 12,
    // Same SurfaceView stack pattern as partnerFlagChip (RTCView zOrder 0).
    zIndex: 280,
    elevation: 20,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: "rgba(6, 10, 18, 0.72)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.18)",
    shadowColor: "#000",
    shadowOpacity: 0.4,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
  },
  partnerCallTimerText: {
    color: "#e8eef7",
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0.3,
    fontVariant: ["tabular-nums"],
    includeFontPadding: false,
    textShadowColor: "rgba(0,0,0,0.85)",
    textShadowRadius: 4,
    textShadowOffset: { width: 0, height: 1 },
  },
  /** Compact call timer when partner is in PiP (swapped views). */
  partnerCallTimerChipPip: {
    position: "absolute",
    left: 6,
    bottom: 6,
    zIndex: 24,
    elevation: 16,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: "rgba(6, 10, 18, 0.78)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.18)",
  },
  partnerCallTimerTextPip: {
    color: "#e8eef7",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.2,
    fontVariant: ["tabular-nums"],
    includeFontPadding: false,
  },
  /**
   * Primary matched identity belt (name / ★ / loc). Compact top-right.
   * elevation must beat nuclear veil coverMain (elev 28) + PartnerBlurVeil
   * (elev 24). Partner RTCView stays zOrder 0 so this RN card wins.
   */
  stagePartnerHud: {
    position: "absolute",
    top: 12,
    right: 10,
    maxWidth: "55%",
    zIndex: 300,
    elevation: 120,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: "rgba(4, 8, 16, 0.94)",
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.35)",
    gap: 2,
    alignItems: "flex-end",
  },
  stagePartnerHudName: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 0.15,
    lineHeight: 18,
    includeFontPadding: false,
    textAlign: "right",
    textShadowColor: "rgba(0,0,0,1)",
    textShadowRadius: 6,
    textShadowOffset: { width: 0, height: 1 },
  },
  stagePartnerHudStars: {
    color: "#ffe566",
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0.15,
    includeFontPadding: false,
    textAlign: "right",
    textShadowColor: "rgba(0,0,0,0.95)",
    textShadowRadius: 4,
    textShadowOffset: { width: 0, height: 1 },
  },
  stagePartnerHudLoc: {
    color: "#d4e4f8",
    fontSize: 11,
    fontWeight: "600",
    textAlign: "right",
    textShadowColor: "rgba(0,0,0,0.85)",
    textShadowRadius: 3,
  },
  stagePartnerHudLocDim: {
    color: "rgba(190, 205, 225, 0.65)",
    fontSize: 11,
    fontWeight: "500",
    textAlign: "right",
  },
  /**
   * @deprecated bottom-of-stage dock — do not remount mid-match.
   * Identity lives in partnerIdentityTopStrip (root absolute under status bar).
   */
  partnerIdentityDock: {
    flexShrink: 0,
    width: "100%",
    minHeight: 48,
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 8,
    gap: 3,
    justifyContent: "center",
    backgroundColor: "rgba(6, 10, 18, 0.97)",
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(255,255,255,0.16)",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(255,255,255,0.1)",
    zIndex: 80,
    elevation: 40,
  },
  /**
   * ONLY matched identity belt: root-level absolute sibling of stage
   * (not nested under RTCView). top/paddingTop applied at runtime via
   * safe-area insets so strip sits just under system status bar.
   *
   * Transparent glass over video — no solid black header (screenshot
   * 2026-08-11 15:01). Max frost rgba(0,0,0,0.25); name/★/loc use
   * strong textShadow for readability over partner video.
   */
  partnerIdentityTopStrip: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    width: "100%",
    // Content-sized — no tall minHeight pushing name/★ down from status bar
    minHeight: 0,
    paddingHorizontal: 12,
    paddingBottom: 4,
    gap: 0,
    justifyContent: "flex-start",
    // Transparent / light frost only — video must show through (never solid panel)
    backgroundColor: "transparent",
    borderWidth: 0,
    borderBottomWidth: 0,
    borderColor: "transparent",
    zIndex: 60,
    elevation: 28,
  },
  /** Horizontal identity row: name · ★ (loc is second full-width line) */
  partnerIdentityDockRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "nowrap",
    gap: 8,
    width: "100%",
  },
  partnerIdentityDockStars: {
    color: "#ffe566",
    fontSize: 16,
    fontWeight: "800",
    letterSpacing: 0.2,
    includeFontPadding: false,
    // Strong shadow — strip is transparent over live video
    textShadowColor: "rgba(0,0,0,1)",
    textShadowRadius: 10,
    textShadowOffset: { width: 0, height: 1 },
  },
  /** ★0 still painted large gold — dimmed, never hidden */
  partnerIdentityDockStarsZero: {
    color: "rgba(255, 210, 80, 0.78)",
    fontSize: 16,
    fontWeight: "800",
    letterSpacing: 0.2,
    includeFontPadding: false,
    textShadowColor: "rgba(0,0,0,1)",
    textShadowRadius: 10,
    textShadowOffset: { width: 0, height: 1 },
  },
  partnerIdentityDockName: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "800",
    letterSpacing: 0.15,
    lineHeight: 20,
    includeFontPadding: false,
    flexShrink: 1,
    textShadowColor: "rgba(0,0,0,1)",
    textShadowRadius: 10,
    textShadowOffset: { width: 0, height: 1 },
  },
  partnerIdentityDockCode: {
    color: "#a8c4e8",
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.2,
    includeFontPadding: false,
  },
  partnerIdentityDockLoc: {
    color: "#e0eaf8",
    fontSize: 12,
    fontWeight: "600",
    lineHeight: 15,
    includeFontPadding: false,
    flexShrink: 1,
    textShadowColor: "rgba(0,0,0,1)",
    textShadowRadius: 8,
    textShadowOffset: { width: 0, height: 1 },
  },
  partnerIdentityDockLocDim: {
    color: "rgba(200, 210, 225, 0.88)",
    fontSize: 12,
    fontWeight: "500",
    lineHeight: 15,
    textShadowColor: "rgba(0,0,0,1)",
    textShadowRadius: 8,
    textShadowOffset: { width: 0, height: 1 },
    includeFontPadding: false,
    flexShrink: 1,
  },
  /** Timer-only when connected (no full conn pill stack) */
  connPillCompact: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(0,0,0,0.4)",
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 999,
  },
  stageLabelBlock: { gap: 2, maxWidth: "90%" },
  stageLabel: {
    color: "#e8eef7",
    fontSize: 14,
    fontWeight: "700",
    textShadowColor: "#000",
    textShadowRadius: 6,
  },
  stagePool: {
    color: "#9ec5ff",
    fontSize: 11,
    fontWeight: "700",
    textShadowColor: "#000",
    textShadowRadius: 4,
  },
  stageQueueAck: {
    color: "#ffe9a0",
    fontSize: 11,
    fontWeight: "600",
    textShadowColor: "#000",
    textShadowRadius: 3,
  },
  stepRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 2,
    marginTop: 4,
    maxWidth: "96%",
  },
  stepItem: {
    flexDirection: "row",
    alignItems: "center",
  },
  stepSep: {
    color: "rgba(255,255,255,0.35)",
    fontSize: 12,
    marginHorizontal: 3,
    fontWeight: "700",
  },
  stepChip: {
    borderRadius: 999,
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderWidth: 1,
  },
  stepChipTodo: {
    backgroundColor: "rgba(0,0,0,0.35)",
    borderColor: "rgba(255,255,255,0.12)",
  },
  stepChipActive: {
    backgroundColor: "rgba(61,126,255,0.35)",
    borderColor: "rgba(120,170,255,0.75)",
  },
  stepChipDone: {
    backgroundColor: "rgba(45,159,111,0.28)",
    borderColor: "rgba(100,220,160,0.55)",
  },
  stepChipText: {
    fontSize: 10,
    fontWeight: "800",
  },
  stepChipTextTodo: { color: "#6b7a90" },
  stepChipTextActive: { color: "#dce8ff" },
  stepChipTextDone: { color: "#b8f5d4" },
  plusPeersLine: {
    color: "#9aa8bc",
    fontSize: 11,
    fontWeight: "600",
    marginTop: 2,
  },
  peerStrip: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 6,
    marginTop: 6,
  },
  partyCount: {
    color: "#9ec5ff",
    fontSize: 11,
    fontWeight: "800",
    marginRight: 2,
  },
  peerChip: {
    backgroundColor: "rgba(0,0,0,0.5)",
    borderRadius: 999,
    paddingVertical: 3,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    maxWidth: "100%",
  },
  peerChipOn: {
    borderColor: "rgba(100,160,255,0.75)",
    backgroundColor: "rgba(40,70,120,0.55)",
  },
  peerChipText: { color: "#c8d4e4", fontSize: 11, fontWeight: "600" },
  /* 3-way / multi: horizontal side-by-side columns (not vertical bands) */
  splitRemote: {
    ...StyleSheet.absoluteFillObject,
    flexDirection: "row",
  },
  splitTile: {
    flex: 1,
    overflow: "hidden",
    borderBottomWidth: 0,
    borderRightWidth: StyleSheet.hairlineWidth,
    borderRightColor: "rgba(255,255,255,0.12)",
  },
  splitTileFocus: {
    flex: 1.15,
    borderRightColor: "rgba(100,160,255,0.35)",
  },
  splitLabel: {
    position: "absolute",
    left: 8,
    bottom: 8,
    color: "#e8eef7",
    fontSize: 12,
    fontWeight: "700",
    textShadowColor: "#000",
    textShadowRadius: 3,
    maxWidth: "90%",
  },
  splitPlaceholder: {
    color: "#e8eef7",
    fontSize: 16,
    fontWeight: "800",
    textAlign: "center",
    letterSpacing: 0.2,
    textShadowColor: "rgba(0,0,0,0.85)",
    textShadowRadius: 8,
  },
  splitPlaceholderSub: {
    color: "#c8d4e4",
    fontSize: 12,
    marginTop: 4,
    textAlign: "center",
    textShadowColor: "rgba(0,0,0,0.8)",
    textShadowRadius: 6,
  },
  splitPlaceholderTap: {
    color: "#9ec5ff",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 12,
    textAlign: "center",
  },
  splitPlaceholderTurn: {
    color: "#6b7a90",
    fontSize: 11,
    fontWeight: "600",
    marginTop: 8,
    textAlign: "center",
  },
  splitPlaceholderHint: {
    color: "rgba(255,255,255,0.45)",
    fontSize: 11,
    fontWeight: "600",
    marginTop: 14,
    textAlign: "center",
  },
  stageRetryChip: {
    marginTop: 14,
    backgroundColor: "rgba(61,126,255,0.92)",
    paddingVertical: 10,
    paddingHorizontal: 22,
    borderRadius: 999,
  },
  stageRetryChipText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "800",
    textAlign: "center",
  },
  /**
   * @deprecated Top-right Report FAB removed — Report lives in bottom bar.
   * Styles kept unused so old references fail softly; do not re-attach on stage.
   */
  stageReportFab: {
    position: "absolute",
    top: 0,
    right: 10,
    zIndex: 40,
    backgroundColor: "rgba(190, 36, 52, 0.88)",
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255, 140, 150, 0.45)",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  /** @deprecated with stageReportFab */
  stageReportFabText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.15,
  },
  stageHint: { color: "#9aa8bc", fontSize: 11, marginTop: 6, lineHeight: 16 },
  connPill: {
    alignSelf: "flex-start",
    marginTop: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: "rgba(0,0,0,0.45)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  connPillOk: {
    borderColor: "rgba(80,220,140,0.55)",
    backgroundColor: "rgba(20,40,28,0.75)",
  },
  connPillSlow: {
    borderColor: "rgba(255,200,80,0.5)",
    backgroundColor: "rgba(40,32,12,0.8)",
  },
  connPillBad: {
    borderColor: "rgba(255,90,100,0.55)",
    backgroundColor: "rgba(40,16,20,0.85)",
  },
  connTimer: {
    color: "#9effc8",
    fontSize: 11,
    fontWeight: "800",
    fontVariant: ["tabular-nums"],
  },
  dataSaverPill: {
    alignSelf: "flex-start",
    marginTop: 6,
    paddingVertical: 3,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: "rgba(40,90,160,0.55)",
    borderWidth: 1,
    borderColor: "rgba(120,180,255,0.4)",
  },
  dataSaverPillText: {
    color: "#c8dcff",
    fontSize: 11,
    fontWeight: "700",
  },
  stayPill: {
    alignSelf: "flex-start",
    marginTop: 6,
    paddingVertical: 3,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: "rgba(80,40,120,0.65)",
    borderWidth: 1,
    borderColor: "rgba(180,140,255,0.5)",
  },
  stayPillText: {
    color: "#e0d0ff",
    fontSize: 11,
    fontWeight: "800",
  },
  btnStayLocked: {
    opacity: 0.75,
    backgroundColor: "rgba(120,80,180,0.55)",
  },
  connPillText: {
    color: "#e8eef7",
    fontSize: 11,
    fontWeight: "700",
  },
  connRetryBtn: {
    backgroundColor: "rgba(61,126,255,0.9)",
    paddingVertical: 3,
    paddingHorizontal: 10,
    borderRadius: 999,
  },
  connHardBtn: {
    backgroundColor: "rgba(255,100,80,0.9)",
  },
  connRetryText: { color: "#fff", fontSize: 11, fontWeight: "800" },
  connQuality: {
    color: "#c8d4e4",
    fontSize: 11,
    fontWeight: "700",
  },
  waitVideoHint: {
    color: "#ffe9a0",
    fontSize: 11,
    marginTop: 6,
    fontWeight: "600",
    textShadowColor: "#000",
    textShadowRadius: 3,
    maxWidth: 260,
  },
  weakLinkHint: {
    color: "#ffc878",
    fontSize: 11,
    marginTop: 4,
    fontWeight: "600",
    maxWidth: 280,
  },
  moreSheet: {
    backgroundColor: "rgba(16,20,30,0.96)",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    overflow: "hidden",
  },
  moreRow: {
    paddingVertical: 13,
    paddingHorizontal: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(255,255,255,0.08)",
  },
  moreRowDanger: {
    backgroundColor: "rgba(255,60,80,0.12)",
  },
  moreRowText: { color: "#e8eef7", fontWeight: "700", fontSize: 14 },
  starProg: { marginTop: 4, gap: 2, maxWidth: 200 },
  starProgTrack: {
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.15)",
    overflow: "hidden",
  },
  starProgFill: {
    height: 4,
    borderRadius: 2,
    backgroundColor: "#ffc850",
  },
  starProgLabel: {
    color: "#ffe9a0",
    fontSize: 11,
    fontWeight: "600",
    textShadowColor: "#000",
    textShadowRadius: 3,
  },
  aloneCard: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 16,
    padding: 14,
    borderRadius: 14,
    backgroundColor: "rgba(16,20,30,0.94)",
    borderWidth: 1,
    borderColor: "rgba(255,200,80,0.35)",
    gap: 6,
  },
  aloneTitle: { color: "#ffe9a0", fontWeight: "800", fontSize: 15 },
  aloneBody: { color: "#c8d4e4", fontSize: 13, lineHeight: 18 },
  aloneCode: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 16,
    letterSpacing: 1,
  },
  aloneBtn: {
    marginTop: 4,
    backgroundColor: "#ff2d55",
    paddingVertical: 10,
    borderRadius: 999,
    alignItems: "center",
  },
  aloneBtnFlex: {
    flex: 1,
    marginTop: 4,
    backgroundColor: "#ff2d55",
    paddingVertical: 10,
    borderRadius: 999,
    alignItems: "center",
  },
  aloneLink: {
    color: "#9ec5ff",
    fontSize: 11,
    lineHeight: 15,
  },
  chatTyping: {
    color: "#9aa8bc",
    fontSize: 11,
    fontStyle: "italic",
    textShadowColor: "#000",
    textShadowRadius: 3,
  },
  /**
   * Safety veil — fully transparent fill so partner/local video stays visible
   * (was a dark slab that looked like “black screen behind camera”).
   * Only the small card remains readable.
   */
  blurOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 11,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 28,
    gap: 10,
  },
  /** Soft frost — near-clear so SurfaceView keeps painting. */
  blurFrostA: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "transparent",
  },
  blurFrostB: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "transparent",
  },
  blurCard: {
    zIndex: 2,
    maxWidth: 320,
    width: "100%",
    alignItems: "center",
    gap: 8,
    paddingVertical: 18,
    paddingHorizontal: 20,
    borderRadius: 18,
    backgroundColor: "rgba(14, 18, 28, 0.55)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  blurTitle: {
    color: "#e8eef7",
    fontSize: 18,
    fontWeight: "800",
    textAlign: "center",
  },
  blurPartner: {
    color: "#c8dcff",
    fontSize: 15,
    fontWeight: "700",
    textAlign: "center",
  },
  blurBody: {
    color: "#b0bdcf",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "center",
  },
  blurBtn: {
    marginTop: 8,
    backgroundColor: "#3d7eff",
    paddingVertical: 12,
    paddingHorizontal: 28,
    borderRadius: 999,
  },
  blurBtnText: { color: "#fff", fontWeight: "800", fontSize: 15 },
  blurBtnReady: {
    backgroundColor: "#2d9f6f",
    borderWidth: 2,
    borderColor: "#6dffb8",
  },
  blurHint: {
    color: "#8a98ad",
    fontSize: 11,
    textAlign: "center",
    marginTop: 4,
  },
  warnCard: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 16,
    padding: 14,
    borderRadius: 14,
    backgroundColor: "rgba(40,16,20,0.96)",
    borderWidth: 1,
    borderColor: "rgba(255,80,100,0.4)",
    gap: 8,
  },
  warnTitle: { color: "#ffb0bc", fontWeight: "800", fontSize: 15 },
  warnBody: { color: "#e0c8cc", fontSize: 13, lineHeight: 18 },
  chatEmptyHint: {
    position: "absolute",
    left: 12,
    right: 100,
    bottom: 16,
    zIndex: 3,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: "rgba(0,0,0,0.28)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  chatEmptyHintText: {
    color: "rgba(210,220,235,0.88)",
    fontSize: 13,
    fontWeight: "600",
  },
  chatOverlay: {
    position: "absolute",
    left: 10,
    right: 96,
    bottom: 10,
    maxHeight: 160,
    borderRadius: 14,
    backgroundColor: "rgba(0,0,0,0.32)",
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  chatOverlayScroll: { maxHeight: 148 },
  chatOverlayContent: {
    gap: 0,
    paddingBottom: 2,
  },
  chatBubbleWrap: {
    alignSelf: "flex-start",
    maxWidth: "88%",
    marginBottom: 5,
  },
  chatBubbleWrapMine: {
    alignSelf: "flex-end",
  },
  chatBubble: {
    borderRadius: 14,
    paddingVertical: 7,
    paddingHorizontal: 11,
    borderWidth: 1,
  },
  chatBubbleTheirs: {
    backgroundColor: "rgba(12, 18, 32, 0.82)",
    borderColor: "rgba(120, 160, 220, 0.22)",
    borderTopLeftRadius: 4,
  },
  chatBubbleMine: {
    backgroundColor: "rgba(40, 90, 200, 0.72)",
    borderColor: "rgba(120, 170, 255, 0.35)",
    borderTopRightRadius: 4,
  },
  chatLine: {
    color: "#e8eef7",
    fontSize: 13,
    lineHeight: 17,
  },
  chatLineMine: {
    color: "#f4f8ff",
  },
  chatFrom: {
    fontWeight: "700",
    color: "#9ec5ff",
    fontSize: 11,
    marginBottom: 2,
  },
  chatTypingWrap: {
    alignSelf: "flex-start",
    marginTop: 2,
  },
  giftSection: {
    paddingTop: 2,
    paddingBottom: 2,
    gap: 4,
  },
  /** Less vertical chrome → taller partner stage (more head/face). */
  giftSectionCompact: {
    paddingTop: 0,
    paddingBottom: 0,
    gap: 2,
  },
  giftUnlockBarCompact: {
    paddingBottom: 0,
    gap: 0,
  },
  giftsScrollCompact: {
    maxHeight: 52,
  },
  giftsRowCompact: {
    paddingBottom: 2,
    paddingTop: 0,
    gap: 6,
  },
  giftChipCompact: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    minWidth: 44,
    borderRadius: 12,
  },
  giftEmojiCompact: { fontSize: 18 },
  giftCostCompact: { fontSize: 10, marginTop: 0 },
  giftSectionHead: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
  },
  giftSectionTitle: {
    color: "#c8d4e4",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  giftBalance: {
    color: "#ffe9a0",
    fontSize: 12,
    fontWeight: "800",
  },
  giftPartnerLine: {
    paddingHorizontal: 14,
    color: "#9aabc2",
    fontSize: 11,
    fontWeight: "600",
  },
  giftUnlockBar: {
    paddingHorizontal: 14,
    paddingBottom: 2,
    gap: 3,
  },
  giftUnlockTrack: {
    height: 3,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.08)",
    overflow: "hidden",
  },
  giftUnlockFill: {
    height: "100%",
    backgroundColor: "rgba(255,200,80,0.75)",
    borderRadius: 2,
  },
  giftUnlockText: {
    color: "#6b7a90",
    fontSize: 10,
    fontWeight: "600",
  },
  giftUnlockReady: {
    color: "#9effc8",
    fontSize: 10,
    fontWeight: "700",
    paddingHorizontal: 14,
    paddingBottom: 2,
  },
  longSearchCard: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 16,
    padding: 14,
    borderRadius: 14,
    backgroundColor: "rgba(20,28,42,0.94)",
    borderWidth: 1,
    borderColor: "rgba(100,150,255,0.35)",
    gap: 8,
    zIndex: 9,
  },
  longSearchTitle: { color: "#c8dcff", fontWeight: "800", fontSize: 14 },
  longSearchBody: { color: "#9aa8bc", fontSize: 12, lineHeight: 17 },
  giftsScroll: {
    maxHeight: 78,
    flexGrow: 0,
  },
  giftsRow: {
    flexDirection: "row",
    flexWrap: "nowrap",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingBottom: 6,
    paddingTop: 2,
  },
  giftChip: {
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.07)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    minWidth: 58,
  },
  giftChipReady: {
    backgroundColor: "rgba(255, 200, 80, 0.12)",
    borderColor: "rgba(255, 200, 80, 0.35)",
  },
  giftChipDisabled: { opacity: 0.38 },
  giftLabel: {
    color: "#b0bccf",
    fontSize: 10,
    fontWeight: "700",
    marginTop: 2,
    maxWidth: 62,
  },
  giftEmoji: { fontSize: 20 },
  giftCost: { color: "#8a96a8", fontSize: 11, fontWeight: "800", marginTop: 1 },
  giftCostReady: { color: "#ffe9a0" },
  rateCard: {
    marginHorizontal: 12,
    marginTop: 8,
    padding: 14,
    borderRadius: 14,
    backgroundColor: "rgba(40,32,12,0.98)",
    borderWidth: 1,
    borderColor: "rgba(255,200,80,0.4)",
    gap: 8,
    zIndex: 50,
  },
  rateTitle: { color: "#ffe9a0", fontWeight: "800", fontSize: 16 },
  rateBody: { color: "#c8d4e4", fontSize: 13, lineHeight: 18 },
  rateGift: {
    flex: 1,
    backgroundColor: "rgba(255,200,80,0.25)",
    paddingVertical: 12,
    borderRadius: 999,
    alignItems: "center",
  },
  chatCount: {
    color: "#6b7a90",
    fontSize: 11,
    fontWeight: "600",
    textAlign: "right",
    marginTop: -4,
    marginBottom: 2,
    paddingHorizontal: 4,
  },
  chatRow: {
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 14,
    paddingBottom: 6,
    alignItems: "center",
  },
  chatInput: {
    flex: 1,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    paddingHorizontal: 16,
    paddingVertical: 11,
    color: "#fff",
    fontSize: 15,
    backgroundColor: "rgba(0,0,0,0.4)",
  },
  chatSend: {
    minWidth: 52,
    minHeight: 44,
    paddingHorizontal: 16,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 999,
    backgroundColor: "rgba(61,126,255,0.92)",
  },
  chatSendText: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 14,
  },
  bar: { paddingHorizontal: 16, paddingBottom: 8, gap: 8 },
  /**
   * Browser-style dock: controls float over full-bleed video (mobile web parity).
   * Used when prefs.liveLayout === "browser".
   */
  // Transparent — same Android SurfaceView rule as native matched root
  rootBrowser: { flex: 1, backgroundColor: "transparent" },
  stageBrowser: {
    ...StyleSheet.absoluteFillObject,
    margin: 0,
    borderRadius: 0,
    backgroundColor: "transparent",
    overflow: "hidden",
  },
  browserDock: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 30,
    paddingHorizontal: 10,
    paddingTop: 8,
    gap: 6,
    backgroundColor: "rgba(4, 8, 14, 0.72)",
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(255,255,255,0.1)",
  },
  browserChatCompose: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    paddingHorizontal: 4,
  },
  browserChatInput: {
    flex: 1,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.16)",
    paddingHorizontal: 14,
    paddingVertical: 10,
    color: "#fff",
    fontSize: 14,
    backgroundColor: "rgba(0,0,0,0.45)",
  },
  browserGifts: {
    maxHeight: 72,
  },
  browserMeta: {
    paddingHorizontal: 4,
    paddingBottom: 2,
  },
  /** Lift chat bubbles above floating browser dock */
  chatOverlayBrowser: {
    bottom: 168,
    right: 12,
    left: 10,
    maxHeight: 140,
    backgroundColor: "rgba(0,0,0,0.38)",
  },
  chatEmptyHintBrowser: {
    bottom: 168,
    right: 100,
  },
  moreSheetBrowser: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 200,
    zIndex: 40,
  },
  meta: { color: "#9aa8bc", fontSize: 12 },
  metaOffline: { color: "#ffe9a0", fontWeight: "700" },
  waitLine: {
    color: "#9ec5ff",
    fontSize: 12,
    fontWeight: "700",
    marginTop: -2,
    marginBottom: 2,
  },
  searchTimerLine: {
    color: "#6b7a90",
    fontSize: 11,
    fontWeight: "600",
    marginTop: -2,
    marginBottom: 2,
  },
  lastHintCard: {
    marginTop: 12,
    maxWidth: 280,
    backgroundColor: "rgba(0,0,0,0.45)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 14,
    gap: 2,
  },
  lastHintLabel: {
    color: "#6b7a90",
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  lastHintName: { color: "#e8eef7", fontSize: 14, fontWeight: "800" },
  lastHintMeta: { color: "#9aa8bc", fontSize: 11, marginTop: 1 },
  friendsOnlyHint: {
    color: "#ffe9a0",
    fontSize: 12,
    lineHeight: 18,
    paddingHorizontal: 4,
    marginBottom: 4,
  },
  row: { flexDirection: "row", gap: 8 },
  btn: {
    flex: 1,
    backgroundColor: "#ff2d55",
    paddingVertical: 14,
    minHeight: 48,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  btnSecondary: {
    flex: 1,
    backgroundColor: "#3d7eff",
    paddingVertical: 14,
    minHeight: 48,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  /** Next is the primary matched action — slightly wider / stronger than Stop. */
  btnNext: {
    flex: 1.35,
    backgroundColor: "#3d7eff",
    paddingVertical: 14,
    minHeight: 48,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(160, 200, 255, 0.45)",
  },
  btnGhost: {
    flex: 0.9,
    backgroundColor: "rgba(255,255,255,0.08)",
    paddingVertical: 14,
    minHeight: 48,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  /** Icon-only control (mic / cam / flip / friends / more). */
  btnIcon: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.08)",
    minHeight: 48,
    paddingVertical: 12,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  btnOff: {
    backgroundColor: "rgba(255,70,90,0.28)",
    borderWidth: 1,
    borderColor: "rgba(255,100,120,0.45)",
  },
  /** Partner audio muted (you can't hear them) — stronger than btnOff */
  btnMuteOn: {
    backgroundColor: "rgba(255, 90, 60, 0.38)",
    borderWidth: 1.5,
    borderColor: "rgba(255, 140, 100, 0.7)",
  },
  /** Privacy veil active */
  btnBlurOn: {
    backgroundColor: "rgba(60, 120, 220, 0.35)",
    borderWidth: 1.5,
    borderColor: "rgba(120, 180, 255, 0.65)",
  },
  btnDanger: {
    flex: 0.95,
    backgroundColor: "rgba(255,80,90,0.38)",
    paddingVertical: 14,
    minHeight: 48,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,100,120,0.5)",
  },
  btnText: { color: "#fff", fontWeight: "700", fontSize: 13 },
  logToggle: {
    color: "#6b7a90",
    fontSize: 11,
    textAlign: "center",
    paddingVertical: 4,
  },
  log: { maxHeight: 100, paddingHorizontal: 16, paddingBottom: 12 },
  logLine: { color: "#6b7a90", fontSize: 10, fontFamily: "monospace" },
  debateChip: {
    position: "absolute",
    top: 52,
    right: 10,
    width: 148,
    padding: 10,
    borderRadius: 14,
    backgroundColor: "rgba(12,16,28,0.92)",
    borderWidth: 1.5,
    borderColor: "rgba(100,140,255,0.55)",
    gap: 3,
    zIndex: 20,
  },
  debateChipMine: {
    borderColor: "rgba(80,220,140,0.75)",
    backgroundColor: "rgba(10,28,18,0.94)",
  },
  debateChipTheirs: {
    borderColor: "rgba(120,140,200,0.5)",
  },
  debateChipUrgent: {
    borderColor: "rgba(255,90,90,0.9)",
    backgroundColor: "rgba(40,12,16,0.95)",
  },
  debateBadge: {
    color: "#9ec5ff",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1,
  },
  debateRound: { color: "#c8d4e4", fontSize: 11, fontWeight: "600" },
  debateTimer: {
    color: "#fff",
    fontSize: 26,
    fontWeight: "800",
    fontVariant: ["tabular-nums"],
  },
  debateTurnLabel: { color: "#e8eef7", fontSize: 11, fontWeight: "700" },
  debateTopic: { color: "#ffe9a0", fontSize: 11, lineHeight: 14 },
  debateProgTrack: {
    height: 3,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.15)",
    overflow: "hidden",
    marginTop: 2,
  },
  debateProgFill: {
    height: 3,
    borderRadius: 2,
    backgroundColor: "#5ad08a",
  },
  debatePassBtn: {
    marginTop: 4,
    backgroundColor: "#3d7eff",
    paddingVertical: 8,
    borderRadius: 999,
    alignItems: "center",
  },
  debateEndBtn: {
    marginTop: 2,
    paddingVertical: 6,
    alignItems: "center",
  },
  debateEndText: { color: "#ff9aa8", fontSize: 11, fontWeight: "700" },
  debateMutedHint: {
    color: "#9aa8bc",
    fontSize: 10,
    fontWeight: "600",
    marginTop: 2,
  },
  debateInviteCard: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 16,
    padding: 14,
    borderRadius: 14,
    backgroundColor: "rgba(16,20,36,0.96)",
    borderWidth: 1,
    borderColor: "rgba(100,140,255,0.45)",
    gap: 6,
    zIndex: 30,
  },
  debateInviteTitle: {
    color: "#c8dcff",
    fontWeight: "800",
    fontSize: 16,
  },
  debateInviteBody: { color: "#c8d4e4", fontSize: 13, lineHeight: 18 },
  debateInviteMeta: { color: "#9aa8bc", fontSize: 12 },
  debateCompose: {
    marginHorizontal: 12,
    marginBottom: 6,
    padding: 14,
    borderRadius: 14,
    backgroundColor: "rgba(16,20,36,0.98)",
    borderWidth: 1,
    borderColor: "rgba(100,140,255,0.4)",
    gap: 8,
  },
  debateComposeLabel: {
    color: "#9aa8bc",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 2,
  },
  debateSecChip: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.08)",
    paddingVertical: 10,
    borderRadius: 999,
    alignItems: "center",
  },
  debateSecChipOn: {
    backgroundColor: "rgba(61,126,255,0.85)",
  },
  debateTopicInput: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: "#fff",
    backgroundColor: "rgba(0,0,0,0.35)",
  },
  debateWaiting: {
    color: "#9ec5ff",
    fontSize: 11,
    textAlign: "center",
    paddingHorizontal: 8,
  },
  statusFlash: {
    position: "absolute",
    left: 16,
    right: 16,
    top: "42%",
    alignItems: "center",
  },
  statusFlashText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
    backgroundColor: "rgba(0,0,0,0.55)",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    overflow: "hidden",
  },
});
