/**
 * Live screen StyleSheet — kept separate so app/live.tsx stays logic-focused.
 */
import { StyleSheet } from "react-native";

export const liveStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#07080c" },
  stage: {
    flex: 1,
    margin: 12,
    borderRadius: 16,
    // Transparent so Android SurfaceView (RTCView) isn't painted over
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    overflow: "hidden",
  },
  remoteFill: { ...StyleSheet.absoluteFillObject },
  /** Edge watermark on partner video */
  brandWm: {
    position: "absolute",
    left: 6,
    top: 0,
    bottom: 0,
    width: 22,
    zIndex: 5,
    justifyContent: "center",
    alignItems: "center",
  },
  brandWmText: {
    color: "rgba(255,255,255,0.42)",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 2,
    transform: [{ rotate: "-90deg" }],
    width: 90,
    textAlign: "center",
    textShadowColor: "rgba(0,0,0,0.75)",
    textShadowRadius: 4,
    textShadowOffset: { width: 0, height: 1 },
  },
  /** Transparent hit target over remote video (must not wrap RTCView). */
  remoteTapLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 3,
    backgroundColor: "transparent",
  },
  /** Soft veil + badge when you mute the partner (debate-style). */
  partnerMuteOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 4,
    justifyContent: "flex-end",
    alignItems: "center",
    paddingBottom: 14,
    backgroundColor: "transparent",
    borderWidth: 2,
    borderColor: "rgba(255, 100, 70, 0.28)",
  },
  partnerMuteWatermark: {
    position: "absolute",
    top: "42%",
    fontSize: 52,
    opacity: 0.28,
    textShadowColor: "rgba(0,0,0,0.55)",
    textShadowRadius: 12,
  },
  partnerMuteBadge: {
    flexDirection: "row",
    alignItems: "center",
    maxWidth: "92%",
    paddingVertical: 7,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: "rgba(40, 12, 10, 0.9)",
    borderWidth: 1,
    borderColor: "rgba(255, 120, 90, 0.55)",
  },
  partnerMuteBadgeText: {
    color: "#ffe8e0",
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  videoPlaceholder: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#12151c",
    alignItems: "center",
    justifyContent: "center",
  },
  pipVideo: { width: "100%", height: "100%" },
  overlay: { position: "absolute", left: 12, top: 12, right: 12, zIndex: 4 },
  stageLabelBlock: { gap: 3, maxWidth: "92%" },
  stageLabel: {
    color: "#e8eef7",
    fontSize: 15,
    fontWeight: "700",
    textShadowColor: "#000",
    textShadowRadius: 4,
  },
  stagePool: {
    color: "#9ec5ff",
    fontSize: 12,
    fontWeight: "700",
    textShadowColor: "#000",
    textShadowRadius: 4,
  },
  stageQueueAck: {
    color: "#ffe9a0",
    fontSize: 11,
    fontWeight: "600",
    textShadowColor: "#000",
    textShadowRadius: 3,
  },
  stepRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 2,
    marginTop: 6,
    maxWidth: "96%",
  },
  stepItem: {
    flexDirection: "row",
    alignItems: "center",
  },
  stepSep: {
    color: "rgba(255,255,255,0.35)",
    fontSize: 12,
    marginHorizontal: 3,
    fontWeight: "700",
  },
  stepChip: {
    borderRadius: 999,
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderWidth: 1,
  },
  stepChipTodo: {
    backgroundColor: "rgba(0,0,0,0.35)",
    borderColor: "rgba(255,255,255,0.12)",
  },
  stepChipActive: {
    backgroundColor: "rgba(61,126,255,0.35)",
    borderColor: "rgba(120,170,255,0.75)",
  },
  stepChipDone: {
    backgroundColor: "rgba(45,159,111,0.28)",
    borderColor: "rgba(100,220,160,0.55)",
  },
  stepChipText: {
    fontSize: 10,
    fontWeight: "800",
  },
  stepChipTextTodo: { color: "#6b7a90" },
  stepChipTextActive: { color: "#dce8ff" },
  stepChipTextDone: { color: "#b8f5d4" },
  plusPeersLine: {
    color: "#9aa8bc",
    fontSize: 11,
    fontWeight: "600",
    marginTop: 2,
  },
  peerStrip: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 6,
    marginTop: 6,
  },
  partyCount: {
    color: "#9ec5ff",
    fontSize: 11,
    fontWeight: "800",
    marginRight: 2,
  },
  peerChip: {
    backgroundColor: "rgba(0,0,0,0.5)",
    borderRadius: 999,
    paddingVertical: 3,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    maxWidth: "100%",
  },
  peerChipOn: {
    borderColor: "rgba(100,160,255,0.75)",
    backgroundColor: "rgba(40,70,120,0.55)",
  },
  peerChipText: { color: "#c8d4e4", fontSize: 11, fontWeight: "600" },
  splitRemote: {
    ...StyleSheet.absoluteFillObject,
    flexDirection: "column",
  },
  splitTile: {
    flex: 1,
    overflow: "hidden",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(255,255,255,0.12)",
  },
  splitTileFocus: {
    flex: 1.35,
    borderBottomColor: "rgba(100,160,255,0.35)",
  },
  splitLabel: {
    position: "absolute",
    left: 8,
    bottom: 8,
    color: "#e8eef7",
    fontSize: 12,
    fontWeight: "700",
    textShadowColor: "#000",
    textShadowRadius: 3,
    maxWidth: "90%",
  },
  splitPlaceholder: {
    color: "#c8d4e4",
    fontSize: 16,
    fontWeight: "700",
    textAlign: "center",
  },
  splitPlaceholderSub: {
    color: "#6b7a90",
    fontSize: 12,
    marginTop: 6,
    textAlign: "center",
  },
  splitPlaceholderTap: {
    color: "#9ec5ff",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 12,
    textAlign: "center",
  },
  splitPlaceholderTurn: {
    color: "#6b7a90",
    fontSize: 11,
    fontWeight: "600",
    marginTop: 8,
    textAlign: "center",
  },
  stageHint: { color: "#9aa8bc", fontSize: 11, marginTop: 6, lineHeight: 16 },
  connPill: {
    alignSelf: "flex-start",
    marginTop: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: "rgba(0,0,0,0.45)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  connPillOk: {
    borderColor: "rgba(80,220,140,0.55)",
    backgroundColor: "rgba(20,40,28,0.75)",
  },
  connPillSlow: {
    borderColor: "rgba(255,200,80,0.5)",
    backgroundColor: "rgba(40,32,12,0.8)",
  },
  connPillBad: {
    borderColor: "rgba(255,90,100,0.55)",
    backgroundColor: "rgba(40,16,20,0.85)",
  },
  connTimer: {
    color: "#9effc8",
    fontSize: 11,
    fontWeight: "800",
    fontVariant: ["tabular-nums"],
  },
  dataSaverPill: {
    alignSelf: "flex-start",
    marginTop: 6,
    paddingVertical: 3,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: "rgba(40,90,160,0.55)",
    borderWidth: 1,
    borderColor: "rgba(120,180,255,0.4)",
  },
  dataSaverPillText: {
    color: "#c8dcff",
    fontSize: 11,
    fontWeight: "700",
  },
  stayPill: {
    alignSelf: "flex-start",
    marginTop: 6,
    paddingVertical: 3,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: "rgba(80,40,120,0.65)",
    borderWidth: 1,
    borderColor: "rgba(180,140,255,0.5)",
  },
  stayPillText: {
    color: "#e0d0ff",
    fontSize: 11,
    fontWeight: "800",
  },
  btnStayLocked: {
    opacity: 0.75,
    backgroundColor: "rgba(120,80,180,0.55)",
  },
  connPillText: {
    color: "#e8eef7",
    fontSize: 11,
    fontWeight: "700",
  },
  connRetryBtn: {
    backgroundColor: "rgba(61,126,255,0.9)",
    paddingVertical: 3,
    paddingHorizontal: 10,
    borderRadius: 999,
  },
  connHardBtn: {
    backgroundColor: "rgba(255,100,80,0.9)",
  },
  connRetryText: { color: "#fff", fontSize: 11, fontWeight: "800" },
  connQuality: {
    color: "#c8d4e4",
    fontSize: 11,
    fontWeight: "700",
  },
  waitVideoHint: {
    color: "#ffe9a0",
    fontSize: 11,
    marginTop: 6,
    fontWeight: "600",
    textShadowColor: "#000",
    textShadowRadius: 3,
    maxWidth: 260,
  },
  weakLinkHint: {
    color: "#ffc878",
    fontSize: 11,
    marginTop: 4,
    fontWeight: "600",
    maxWidth: 280,
  },
  moreSheet: {
    backgroundColor: "rgba(16,20,30,0.96)",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    overflow: "hidden",
  },
  moreRow: {
    paddingVertical: 13,
    paddingHorizontal: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(255,255,255,0.08)",
  },
  moreRowDanger: {
    backgroundColor: "rgba(255,60,80,0.12)",
  },
  moreRowText: { color: "#e8eef7", fontWeight: "700", fontSize: 14 },
  starProg: { marginTop: 8, gap: 4, maxWidth: 220 },
  starProgTrack: {
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.15)",
    overflow: "hidden",
  },
  starProgFill: {
    height: 4,
    borderRadius: 2,
    backgroundColor: "#ffc850",
  },
  starProgLabel: {
    color: "#ffe9a0",
    fontSize: 11,
    fontWeight: "600",
    textShadowColor: "#000",
    textShadowRadius: 3,
  },
  aloneCard: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 16,
    padding: 14,
    borderRadius: 14,
    backgroundColor: "rgba(16,20,30,0.94)",
    borderWidth: 1,
    borderColor: "rgba(255,200,80,0.35)",
    gap: 6,
  },
  aloneTitle: { color: "#ffe9a0", fontWeight: "800", fontSize: 15 },
  aloneBody: { color: "#c8d4e4", fontSize: 13, lineHeight: 18 },
  aloneCode: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 16,
    letterSpacing: 1,
  },
  aloneBtn: {
    marginTop: 4,
    backgroundColor: "#ff2d55",
    paddingVertical: 10,
    borderRadius: 999,
    alignItems: "center",
  },
  aloneBtnFlex: {
    flex: 1,
    marginTop: 4,
    backgroundColor: "#ff2d55",
    paddingVertical: 10,
    borderRadius: 999,
    alignItems: "center",
  },
  aloneLink: {
    color: "#9ec5ff",
    fontSize: 11,
    lineHeight: 15,
  },
  chatTyping: {
    color: "#9aa8bc",
    fontSize: 11,
    fontStyle: "italic",
    textShadowColor: "#000",
    textShadowRadius: 3,
  },
  /**
   * Safety veil over live partner video — NOT a solid black wall.
   * Semi-transparent frost so RTCView keeps painting underneath (Android).
   */
  blurOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 11,
    backgroundColor: "rgba(10, 12, 18, 0.48)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 28,
    gap: 10,
  },
  /** Soft frost layers — fakes blur without native BlurView / SurfaceView issues. */
  blurFrostA: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(180, 195, 220, 0.12)",
  },
  blurFrostB: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(8, 10, 16, 0.28)",
  },
  blurCard: {
    zIndex: 2,
    maxWidth: 320,
    width: "100%",
    alignItems: "center",
    gap: 8,
    paddingVertical: 18,
    paddingHorizontal: 20,
    borderRadius: 18,
    backgroundColor: "rgba(14, 18, 28, 0.78)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  blurTitle: {
    color: "#e8eef7",
    fontSize: 18,
    fontWeight: "800",
    textAlign: "center",
  },
  blurPartner: {
    color: "#c8dcff",
    fontSize: 15,
    fontWeight: "700",
    textAlign: "center",
  },
  blurBody: {
    color: "#b0bdcf",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "center",
  },
  blurBtn: {
    marginTop: 8,
    backgroundColor: "#3d7eff",
    paddingVertical: 12,
    paddingHorizontal: 28,
    borderRadius: 999,
  },
  blurBtnText: { color: "#fff", fontWeight: "800", fontSize: 15 },
  blurBtnReady: {
    backgroundColor: "#2d9f6f",
    borderWidth: 2,
    borderColor: "#6dffb8",
  },
  blurHint: {
    color: "#8a98ad",
    fontSize: 11,
    textAlign: "center",
    marginTop: 4,
  },
  warnCard: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 16,
    padding: 14,
    borderRadius: 14,
    backgroundColor: "rgba(40,16,20,0.96)",
    borderWidth: 1,
    borderColor: "rgba(255,80,100,0.4)",
    gap: 8,
  },
  warnTitle: { color: "#ffb0bc", fontWeight: "800", fontSize: 15 },
  warnBody: { color: "#e0c8cc", fontSize: 13, lineHeight: 18 },
  chatEmptyHint: {
    position: "absolute",
    left: 12,
    right: 100,
    bottom: 16,
    zIndex: 3,
  },
  chatEmptyHintText: {
    color: "rgba(200,212,228,0.75)",
    fontSize: 12,
    fontWeight: "600",
  },
  chatOverlay: {
    position: "absolute",
    left: 12,
    right: 100,
    bottom: 12,
    maxHeight: 140,
    borderRadius: 12,
    backgroundColor: "rgba(0,0,0,0.4)",
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  chatOverlayScroll: { maxHeight: 128 },
  chatOverlayContent: {
    gap: 2,
  },
  chatLine: {
    color: "#e8eef7",
    fontSize: 12,
    textShadowColor: "#000",
    textShadowRadius: 3,
  },
  chatFrom: { fontWeight: "700", color: "#9ec5ff" },
  giftUnlockBar: {
    paddingHorizontal: 14,
    paddingBottom: 4,
    gap: 4,
  },
  giftUnlockTrack: {
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.1)",
    overflow: "hidden",
  },
  giftUnlockFill: {
    height: "100%",
    backgroundColor: "rgba(255,200,80,0.85)",
    borderRadius: 2,
  },
  giftUnlockText: {
    color: "#9aa8bc",
    fontSize: 11,
    fontWeight: "600",
  },
  giftUnlockReady: {
    color: "#9effc8",
    fontSize: 11,
    fontWeight: "700",
    paddingHorizontal: 14,
    paddingBottom: 4,
  },
  longSearchCard: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 16,
    padding: 14,
    borderRadius: 14,
    backgroundColor: "rgba(20,28,42,0.94)",
    borderWidth: 1,
    borderColor: "rgba(100,150,255,0.35)",
    gap: 8,
    zIndex: 9,
  },
  longSearchTitle: { color: "#c8dcff", fontWeight: "800", fontSize: 14 },
  longSearchBody: { color: "#9aa8bc", fontSize: 12, lineHeight: 17 },
  giftsScroll: {
    maxHeight: 64,
    flexGrow: 0,
  },
  giftsRow: {
    flexDirection: "row",
    flexWrap: "nowrap",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingBottom: 4,
  },
  giftChip: {
    alignItems: "center",
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.08)",
    minWidth: 52,
  },
  giftChipDisabled: { opacity: 0.4 },
  giftLabel: {
    color: "#9aa8bc",
    fontSize: 9,
    fontWeight: "600",
    marginTop: 1,
    maxWidth: 56,
  },
  giftEmoji: { fontSize: 16 },
  giftCost: { color: "#9aa8bc", fontSize: 10, fontWeight: "700" },
  rateCard: {
    marginHorizontal: 12,
    marginTop: 8,
    padding: 14,
    borderRadius: 14,
    backgroundColor: "rgba(40,32,12,0.98)",
    borderWidth: 1,
    borderColor: "rgba(255,200,80,0.4)",
    gap: 8,
    zIndex: 50,
  },
  rateTitle: { color: "#ffe9a0", fontWeight: "800", fontSize: 16 },
  rateBody: { color: "#c8d4e4", fontSize: 13, lineHeight: 18 },
  rateGift: {
    flex: 1,
    backgroundColor: "rgba(255,200,80,0.25)",
    paddingVertical: 12,
    borderRadius: 999,
    alignItems: "center",
  },
  chatCount: {
    color: "#6b7a90",
    fontSize: 11,
    fontWeight: "600",
    textAlign: "right",
    marginTop: -4,
    marginBottom: 2,
    paddingHorizontal: 4,
  },
  chatRow: {
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 16,
    paddingBottom: 4,
  },
  chatInput: {
    flex: 1,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    paddingHorizontal: 14,
    paddingVertical: 10,
    color: "#fff",
    backgroundColor: "rgba(0,0,0,0.35)",
  },
  chatSend: {
    paddingHorizontal: 16,
    justifyContent: "center",
    borderRadius: 999,
    backgroundColor: "rgba(61,126,255,0.85)",
  },
  bar: { paddingHorizontal: 16, paddingBottom: 8, gap: 8 },
  meta: { color: "#9aa8bc", fontSize: 12 },
  metaOffline: { color: "#ffe9a0", fontWeight: "700" },
  waitLine: {
    color: "#9ec5ff",
    fontSize: 12,
    fontWeight: "700",
    marginTop: -2,
    marginBottom: 2,
  },
  searchTimerLine: {
    color: "#6b7a90",
    fontSize: 11,
    fontWeight: "600",
    marginTop: -2,
    marginBottom: 2,
  },
  lastHintCard: {
    marginTop: 12,
    maxWidth: 280,
    backgroundColor: "rgba(0,0,0,0.45)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 14,
    gap: 2,
  },
  lastHintLabel: {
    color: "#6b7a90",
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  lastHintName: { color: "#e8eef7", fontSize: 14, fontWeight: "800" },
  lastHintMeta: { color: "#9aa8bc", fontSize: 11, marginTop: 1 },
  friendsOnlyHint: {
    color: "#ffe9a0",
    fontSize: 12,
    lineHeight: 18,
    paddingHorizontal: 4,
    marginBottom: 4,
  },
  row: { flexDirection: "row", gap: 8 },
  btn: {
    flex: 1,
    backgroundColor: "#ff2d55",
    paddingVertical: 14,
    minHeight: 48,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  btnSecondary: {
    flex: 1,
    backgroundColor: "#3d7eff",
    paddingVertical: 14,
    minHeight: 48,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  btnGhost: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.08)",
    paddingVertical: 14,
    minHeight: 48,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  /** Icon-only control (mic / cam / flip / friends / more). */
  btnIcon: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.08)",
    minHeight: 48,
    paddingVertical: 12,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  btnOff: {
    backgroundColor: "rgba(255,70,90,0.28)",
    borderWidth: 1,
    borderColor: "rgba(255,100,120,0.45)",
  },
  btnDanger: {
    flex: 1,
    backgroundColor: "rgba(255,80,90,0.38)",
    paddingVertical: 14,
    minHeight: 48,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,100,120,0.5)",
  },
  btnText: { color: "#fff", fontWeight: "700", fontSize: 13 },
  logToggle: {
    color: "#6b7a90",
    fontSize: 11,
    textAlign: "center",
    paddingVertical: 4,
  },
  log: { maxHeight: 100, paddingHorizontal: 16, paddingBottom: 12 },
  logLine: { color: "#6b7a90", fontSize: 10, fontFamily: "monospace" },
  debateChip: {
    position: "absolute",
    top: 52,
    right: 10,
    width: 148,
    padding: 10,
    borderRadius: 14,
    backgroundColor: "rgba(12,16,28,0.92)",
    borderWidth: 1.5,
    borderColor: "rgba(100,140,255,0.55)",
    gap: 3,
    zIndex: 20,
  },
  debateChipMine: {
    borderColor: "rgba(80,220,140,0.75)",
    backgroundColor: "rgba(10,28,18,0.94)",
  },
  debateChipTheirs: {
    borderColor: "rgba(120,140,200,0.5)",
  },
  debateChipUrgent: {
    borderColor: "rgba(255,90,90,0.9)",
    backgroundColor: "rgba(40,12,16,0.95)",
  },
  debateBadge: {
    color: "#9ec5ff",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1,
  },
  debateRound: { color: "#c8d4e4", fontSize: 11, fontWeight: "600" },
  debateTimer: {
    color: "#fff",
    fontSize: 26,
    fontWeight: "800",
    fontVariant: ["tabular-nums"],
  },
  debateTurnLabel: { color: "#e8eef7", fontSize: 11, fontWeight: "700" },
  debateTopic: { color: "#ffe9a0", fontSize: 11, lineHeight: 14 },
  debateProgTrack: {
    height: 3,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.15)",
    overflow: "hidden",
    marginTop: 2,
  },
  debateProgFill: {
    height: 3,
    borderRadius: 2,
    backgroundColor: "#5ad08a",
  },
  debatePassBtn: {
    marginTop: 4,
    backgroundColor: "#3d7eff",
    paddingVertical: 8,
    borderRadius: 999,
    alignItems: "center",
  },
  debateEndBtn: {
    marginTop: 2,
    paddingVertical: 6,
    alignItems: "center",
  },
  debateEndText: { color: "#ff9aa8", fontSize: 11, fontWeight: "700" },
  debateMutedHint: {
    color: "#9aa8bc",
    fontSize: 10,
    fontWeight: "600",
    marginTop: 2,
  },
  debateInviteCard: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 16,
    padding: 14,
    borderRadius: 14,
    backgroundColor: "rgba(16,20,36,0.96)",
    borderWidth: 1,
    borderColor: "rgba(100,140,255,0.45)",
    gap: 6,
    zIndex: 30,
  },
  debateInviteTitle: {
    color: "#c8dcff",
    fontWeight: "800",
    fontSize: 16,
  },
  debateInviteBody: { color: "#c8d4e4", fontSize: 13, lineHeight: 18 },
  debateInviteMeta: { color: "#9aa8bc", fontSize: 12 },
  debateCompose: {
    marginHorizontal: 12,
    marginBottom: 6,
    padding: 14,
    borderRadius: 14,
    backgroundColor: "rgba(16,20,36,0.98)",
    borderWidth: 1,
    borderColor: "rgba(100,140,255,0.4)",
    gap: 8,
  },
  debateComposeLabel: {
    color: "#9aa8bc",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 2,
  },
  debateSecChip: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.08)",
    paddingVertical: 10,
    borderRadius: 999,
    alignItems: "center",
  },
  debateSecChipOn: {
    backgroundColor: "rgba(61,126,255,0.85)",
  },
  debateTopicInput: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: "#fff",
    backgroundColor: "rgba(0,0,0,0.35)",
  },
  debateWaiting: {
    color: "#9ec5ff",
    fontSize: 11,
    textAlign: "center",
    paddingHorizontal: 8,
  },
  statusFlash: {
    position: "absolute",
    left: 16,
    right: 16,
    top: "42%",
    alignItems: "center",
  },
  statusFlashText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
    backgroundColor: "rgba(0,0,0,0.55)",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    overflow: "hidden",
  },
});
