#!/usr/bin/env bash
# Install coturn and wire roulette-bridge to self-hosted TURN.
# Run as root on the droplet (or via push after upload).
set -euo pipefail

DOMAIN="${DOMAIN:-ruletka.vip}"
APP_DIR="${APP_DIR:-/opt/ruletka}"
PUBLIC_IP="${PUBLIC_IP:-$(curl -4 -fsS --max-time 5 ifconfig.me || curl -4 -fsS --max-time 5 icanhazip.com || true)}"
PUBLIC_IP="${PUBLIC_IP//[$'\t\r\n ']/}"
# Map external-ip=PUBLIC/PUBLIC (self). DO on-host public + VPC private must NOT
# use PUBLIC/VPC: coturn rewrites CreatePermission peers to VPC while sockets
# bind public → peer_usage=0. Self-map whitelists relay↔relay hairpin.

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Run as root"
  exit 1
fi

if [[ -z "$PUBLIC_IP" ]]; then
  echo "Could not detect PUBLIC_IP"
  exit 1
fi

export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y coturn openssl

# Shared secret (bridge + coturn)
mkdir -p "$APP_DIR/data" /var/log/turnserver
chown turnserver:turnserver /var/log/turnserver 2>/dev/null || true

if [[ ! -f "$APP_DIR/data/turn.env" ]]; then
  SECRET=$(openssl rand -hex 32)
  cat >"$APP_DIR/data/turn.env" <<EOF
# Generated by setup-turn.sh — do not commit
ROULETTE_TURN_SECRET=${SECRET}
ROULETTE_TURN_TTL=21600
EOF
  chmod 640 "$APP_DIR/data/turn.env"
  chown root:ruletka "$APP_DIR/data/turn.env" 2>/dev/null || chown root:root "$APP_DIR/data/turn.env"
  echo "Created $APP_DIR/data/turn.env"
else
  # shellcheck disable=SC1090
  source "$APP_DIR/data/turn.env"
  SECRET="${ROULETTE_TURN_SECRET:-}"
  if [[ -z "$SECRET" ]]; then
    echo "turn.env exists but ROULETTE_TURN_SECRET empty"
    exit 1
  fi
  echo "Using existing turn secret from turn.env"
fi

# Install coturn config from template if present, else inline
TEMPLATE="$APP_DIR/deploy/coturn.conf"
if [[ -f "$TEMPLATE" ]]; then
  sed -e "s/__TURN_SECRET__/${SECRET//\//\\/}/g" \
      -e "s/__PUBLIC_IP__/${PUBLIC_IP}/g" \
      -e "s/__PRIVATE_IP__/${PUBLIC_IP}/g" \
      "$TEMPLATE" >/etc/turnserver.conf
else
  # PUBLIC/PUBLIC: self-peer whitelist without VPC rewrite blackhole
  cat >/etc/turnserver.conf <<EOF
listening-ip=0.0.0.0
listening-port=3478
min-port=49160
max-port=50000
fingerprint
use-auth-secret
static-auth-secret=${SECRET}
realm=${DOMAIN}
server-name=${DOMAIN}
external-ip=${PUBLIC_IP}/${PUBLIC_IP}
no-multicast-peers
no-cli
simple-log
log-file=/var/log/turnserver/turn.log
verbose
EOF
fi

# Enable coturn daemon
if [[ -f /etc/default/coturn ]]; then
  sed -i 's/^#\?TURNSERVER_ENABLED=.*/TURNSERVER_ENABLED=1/' /etc/default/coturn
  grep -q '^TURNSERVER_ENABLED=1' /etc/default/coturn || echo 'TURNSERVER_ENABLED=1' >>/etc/default/coturn
fi

# Firewall (must cover min-port..max-port from coturn.conf)
ufw allow 3478/tcp comment 'TURN'
ufw allow 3478/udp comment 'TURN'
ufw allow 49160:50000/udp comment 'TURN relay'
ufw allow 49160:50000/tcp comment 'TURN relay'
yes | ufw enable || true
ufw status | head -30 || true

systemctl enable coturn
systemctl restart coturn
sleep 1
systemctl --no-pager --full status coturn | head -20 || true

# Ensure bridge service loads turn.env and disables open relay
# (service unit is also updated in repo; reinstall if present)
if [[ -f "$APP_DIR/deploy/roulette-bridge.service" ]]; then
  install -m 644 "$APP_DIR/deploy/roulette-bridge.service" /etc/systemd/system/roulette-bridge.service
fi
systemctl daemon-reload
systemctl restart roulette-bridge
sleep 1

echo "=== health ==="
curl -sS http://127.0.0.1:8790/health || true
echo
echo "=== config.json turn snippet ==="
curl -sS http://127.0.0.1:8790/config.json | head -c 2000 || true
echo
echo "TURN public: turn:${DOMAIN}:3478 (UDP/TCP) on ${PUBLIC_IP}"
echo "Relay UDP/TCP: 49160-50000 (external-ip=${PUBLIC_IP}/${PUBLIC_IP})"
echo "Done."
